package CS225FinalProject.GUI;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JOptionPane;

import CS225FinalProject.SimulationManager;
import CS225FinalProject.DataStructure.SimulationController;
import CS225FinalProject.DataStructure.User;

/**
 * Prototype Diaolog sss
 * 
 * @author Eric Santana
 */
public class LoginGUI extends javax.swing.JDialog {

	private SimulationManager manager;
	private SimulationController controller = SimulationController
			.getInstance();

	/**
	 * Creates new form LoginGUI
	 */
	public LoginGUI(java.awt.Frame parent, boolean modal,
			SimulationManager manager) {
		super(parent, modal);
                setTitle("MassBay General Hospital Login");
		initComponents();
		this.manager = manager;
		setLocation((getToolkit().getScreenSize().width - getWidth()) / 2,
				(getToolkit().getScreenSize().height - getHeight()) / 2);
		addWindowListener(new WindowAdapter() {

			@Override
			public void windowClosing(WindowEvent e) {
				System.exit(0);

			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("UserName:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 103, 65, 27));

        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 150, -1));

        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 139, -1, -1));

        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 150, -1));

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/massachusetts-bay-community-college.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 11, -1, -1));

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_usernameTextFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_usernameTextFieldActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		if(usernameTextField.getText().equals("test")&& new String(passwordField.getPassword()).equals("test")){
                    SimulationManager.state = SimulationManager.SCENARIO_STATE;
                    setVisible(false);
                    usernameTextField.setText("");
			passwordField.setText("");
                        return;
                }
            
            
		if (controller.validateStudentLogin(usernameTextField.getText(),
				new String(passwordField.getPassword()))) {
			SimulationManager.state = SimulationManager.SCENARIO_STATE;
			setVisible(false);
			usernameTextField.setText("");
			passwordField.setText("");
		} 
                else if(controller.validateInstructorLogin(usernameTextField.getText(),
				new String(passwordField.getPassword()))){
                    SimulationManager.state = SimulationManager.MAINTENANCE_STATE;
			setVisible(false);
			usernameTextField.setText("");
			passwordField.setText("");
                    
                }
                else
                    JOptionPane.showMessageDialog(this, "Your login is not correct");

	}// GEN-LAST:event_jButton1ActionPerformed

	private void professorLoginButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_professorLoginButtonActionPerformed

		if (controller.validateInstructorLogin(usernameTextField.getText(),
				new String(passwordField.getPassword()))) {
			SimulationManager.state = SimulationManager.MAINTENANCE_STATE;
			setVisible(false);
			usernameTextField.setText("");
			passwordField.setText("");
		} else
			JOptionPane.showMessageDialog(this, "Your login is not correct");

	}// GEN-LAST:event_professorLoginButtonActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		System.exit(0);
	}// GEN-LAST:event_jButton2ActionPerformed

	private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_passwordFieldKeyPressed
		// TODO add your handling code here:
		if (evt.getKeyCode() == KeyEvent.VK_ENTER)
			jButton1.getActionListeners()[0]
					.actionPerformed(new ActionEvent(jButton1, 0,
							null));
	}// GEN-LAST:event_passwordFieldKeyPressed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/*
		 * Set the Nimbus look and feel
		 */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/*
		 * Create and display the dialog
		 */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				LoginGUI dialog = new LoginGUI(new javax.swing.JFrame(), true,
						null);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {

					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
